#!/bin/bash

UDESC_CA_PORT=7054
PUBLIC_CA_PORT=8054

UDESC_ANCHOR_PEER_PORT=7051
PUBLIC_ANCHOR_PEER_PORT=9051

UDESC_PEERS_PORTS=($UDESC_ANCHOR_PEER_PORT 7055 7057)
UDESC_PEERS_NAMES=("CEAVI" "CCT" "CEPLAN") 
PUBLIC_PEERS_PORTS=($PUBLIC_ANCHOR_PEER_PORT)